version: "3.8"
services:
  db:
    image: library/mysql:8
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=app
  php74:
    build:
      context: ./
      dockerfile: php7.4.Dockerfile
    image: gusdecool/symfony:7.4
    ports:
      - 6001:80
      - 6002:443
    volumes:
      - ./symfony:/app
      - composer_cache:/root/.composer/cache
  php8:
    build:
      context: ./
      dockerfile: php8.Dockerfile
    image: gusdecool/symfony:8
    ports:
      - 6003:80
      - 6004:443
    volumes:
      - ./symfony:/app
      - composer_cache:/root/.composer/cache
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    depends_on:
      - db
volumes:
  composer_cache:
  yarn_cache:
  db_data:
