version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build image
                  command: docker build -t gusdecool/symfony .
